### ISSUE TITLE
problems with relatedMessages

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork-threads#11]
Using relatedMessages thrashes the database, and we need to fix it.
Really, I think we should stop using relatedMessages all together.
patchwork uses relatedMessages without setting a rel, which means that for every message, it gets every message that is related to it, recursively.

Since each message in a thread uses root AND branch links, that means a message is included twice in the tree. And if a thread is mentioned elsewhere, then it gets even more links attached into the related messages tree.

Consequently, there are threads that have hundreds of "related messages" and may take seconds to load, but this is just a mistake and there is no reason it can't be fast.

However, part of the problem is that patchwork-threads rely on a single call to get everything about a thread in one go, the thread posts, the likes, the backlinks. it gets it all in the relatedMessages response, and then flattens and figures out what it doesn't need. So a lot of stuff is coupled together here.

here is a list of threads that take more than 500 ms to load on my laptop:

```
#id loadtime count loadtime_dedup count_dedup
%+tLYIXlT6tzJeOZmU731DQXpUXLvDsTqLzC7au9sLgY=.sha256 1743 238 279 33
%+hSdTLOoUpBMqHUMF8LuXg/T0W+aPsyesZtUelk8VfU=.sha256 1741 133 224 30
%WHO8mZoRqAnYGNxCdkgittFD38DqW0iSr7xxS9fi4tg=.sha256 1458 15 428 14
%enY+X5IpdI+GpETc8zTpkxGXlYy9R3iDUjVO95wYqv8=.sha256 1483 166 342 46
%vPvLzkAoJa0FqAXtXdHNZOMkWJEWHiy21cZY4iu8Vjo=.sha256 1655 114 221 27
%yGzlltGko4Zbkf3KFqo68J0E4oHUdcCZH3Ar6PVfRMo=.sha256 1464 13 424 13
%GdLEQtwr68GeSWzB+p6pG8RpOaIg4qSzCUWy0arctUg=.sha256 1499 79 221 24
%/3ewFvKSXkvX+Y9J9+raRz3WWiu0EezlNhk2H42MBiE=.sha256 1083 1 194 1
%3LExg6ChCYIM/oYYN0CcNV2uQuhhOCmDGf4WyhqpmpY=.sha256 1083 3 195 3
%lT8T8019N+X9k9f5zevlYVVbwyQDsLp+bsNlTuk+sBk=.sha256 1254 20 202 10
%Davde0GJlEHn6kXRHwvv48ihIN9OHbW8wBLbdiQbiJs=.sha256 522 91 759 26
%UhgGOZYBZlxNVaPstKraee+UQLLQeMImjDI6C9Z1mXU=.sha256 759 6 346 5
%/28VPlNKpJt55gHJpZ2TvIxAqIoFzfjUlt9vAhcEC84=.sha256 987 15 237 9
%qt95C6J1lTvEBBQdrJYHVrGOA43OIvt8W6D7tnQk7KM=.sha256 2025 834 464 82
1712PHYEnDwAq/F9itzvQwMxW+WYFRidXAaXZTHiF38PXg=.sha256 362 628 69
%8W/ePQ1f3mYtIRYHYZawkSy4gMbZkpHmIg/RP2jj+FE=.sha256 1384 74 433 27
%abv/JjVgt9gBMscBjFRxtG61Z9MQAKG0RQBMo1kSSlg=.sha256 1098 25 220 12
%zZk1h5NIRrtR9MGaMj9ue3Lsn9+kkZAzwHlBvwodsDk=.sha256 1613 149 432 34
%4bwdizRDb+4iNLzj7xCPE6bqzDwwEWJvuA5VGOe7tFs=.sha256 840 5 432 4
%3lw671dpL+w4hUdGCZcNEmMm9CWsMSQAOv+WNQKrqIM=.sha256 840 5 227 4
%iM3L2ZaCUTQ589BkY3qM72ggCEYVtGEmZ5iJmWxF2yU=.sha256 1534 122 433 30
%tZaohfYyVX0qKJ/CSaqJv/JNp4k55dR6htxk/PeCay0=.sha256 839 6 227 5
%8Wr10nTALyUkAVGrj8uwOf1kTYB05XOG4KzxpOKab4E=.sha256 1254 9 653 9
%EGBRabvmdgNHMkXs85SddI69Q07diTxhQGmwLzLqo5I=.sha256 840 8 227 7
%DW5La8hE1nJjMKu2cbpDGOhkT+v88RBnQcJnysb0bLk=.sha256 901 15 227 12
%G2XI9+RiKTl6eyydWHYS5lV3cjZmHztYhAoFvQal/VA=.sha256 901 10 433 6
%Zundhf6gzpYAaePD+8DBeE7MDqull81LSCcTBfkGjPw=.sha256 1179 29 433 12
%6jcXcVJVP9RP8Bwy0Haq7dXseHnCN/yOmI0o9VY27hA=.sha256 1433 87 434 24
%abuBmDWBJO96on4sF0B1ruUqbpeSedJ040dL6KvCDA8=.sha256 1533 134 437 34
%T4/DaE0guGgJqYuTJwjavc85FZhHl6zNfCLYFwRcsLE=.sha256 1073 175 780 62
%e1zrHt9l3Wz5w9tw45s2wf9+PEfAlnxdLVQl2QFBVww=.sha256 821 89 1215 59
%yAvDwopppOmCXAU5xj5KOuLkuYp+CkUicmEJbgJVrbo=.sha256 717 54 224 18
626/U0NvzBF5zwUcQ8U/AohHAmnfuR+xD7/JmL6B8YmuQ=.sha256 35 261 18
%KHbuMvvydIrbLMQ46JYH07q8HpRV57M/533InfVeGf4=.sha256 717 122 470 53
%bUS+3uadb2BjuFbVTs6e7/a4aZshposMt7YaUfRBVYU=.sha256 684 92 407 33
623eUEAo7PTyA7vNwnOrmGIsUFfpyRzOvzGVv1QCb/Fz8=.sha256 85 294 27
%2/y/djFmYaSmfGwTBMI//Pv7/UhZeqAd7Pd/2yomXbE=.sha256 597 50 352 30
%4lh+Z5PYpS1bnCmH84Ly2ilB0FLKUkbqNam3vgpFKCs=.sha256 810 341 186 60
%87E9BOi3QbwbWoJztKE2TE7w0EQ5PiWi35HlfqB8mrQ=.sha256 725 296 275 42
%3Ugo50V6uOdyaMEgySLy4UtYWaBf3UzVgokXdk8p8ro=.sha256 746 305 210 45
%2MVpCykgHUdUmu6qeSl7A3GaDDlUKtBBh0oVGT+qECg=.sha256 629 107 172 32
%cXc8ugLWfzYXcbAnZUDzYFZo+NV3AeyS3LxZpxCExrM=.sha256 703 447 204 57
%/dyvTBDtQIw9wvUMP4+KvpOHr5MnFpBA7WSg9BdMT+w=.sha256 1984 1139 796 128
%cT1NP++P18NqLE2qnbwXmbZ2biVJh+usgSGkhJJDlqk=.sha256 504 170 135 33
%uf9LSf1MEIY9Q3nYDgr9hRV06QhksrQyHQcE6ztQHjo=.sha256 561 389 151 49
%QgM2/+huObkjoznixnJIRp/39b8gg0kTVu2yRkBTKS8=.sha256 570 447 491 95
%9L8PB5l5oBf5p1kyEr77izJgty5QwEfJMlshZz8TUzs=.sha256 689 313 145 47
%coYbAvKZh5O0BVE1+donSi72Z042fnlmszL/DihZJiw=.sha256 642 232 147 43
%gjaVyS9E/KtbkuS97bwYDq9yoB2Z6+dbpUeiOppEQaI=.sha256 814 170 551 56
%GtPrziKnBANZRL+Za1u0/o+2NH4/bgufiiKXkLk0M9o=.sha256 628 65 269 24
%Xc5qi71bCBsCeQw6Vw7J68Bd/NtIl65wCoV51DoQ9Jo=.sha256 818 196 267 39
%62oz1IOFkN3tL48lNoPUPDe1+zi+ax9H/H1JkiHSE/g=.sha256 630 55 268 19
%pNWKHFussinBWXRhfnPE4BbTSUMTesagKvB3gqsbFdU=.sha256 699 66 268 22
%gzTyHZvVvuuVTRD9+9Rbt+LmO9pvvxGU6yiG/0lcy2Y=.sha256 559 37 269 15
%T9HdR5DRX5LDxIyx4ciCoUdGlhf316rQkMNHBbB4Mrc=.sha256 621 62 272 26
%7G0kC/rzBW0WXmC4SMlNNxTG9li0Iwucx2u91lBBMKg=.sha256 1351 839 301 77
%BBrt8L/ldJ8L6+niv7fHwTFzaR0UrmeChfVGtP1jJzY=.sha256 572 37 169 16
%MJfxamw0j7z2hrxnAZf3so6kyPwz2FtT87/72lIQ+Sk=.sha256 1229 744 524 70
%KpBlOkee8yiw/JU4LQ/hcPQpIgPUwha3dPanFEE5tHI=.sha256 1081 185 215 44
%9WOe6GEi5qASDSWO//HwVhR4KcNgWy7Dkc6pGz2l8KU=.sha256 549 95 251 24
%qytjd+XrceK2bBrtA5dhv9AFBC1rDYBnMWQpFumx/CU=.sha256 649 258 96 41
%a6PriQaGiV4L2bmqXiAsDZoSUCkB1hDi9eSk4HCulOs=.sha256 598 417 166 87
```

(this list is cut short because reading some as patchwork does actually causes scuttlebot to crash, but somehow, that doesn't happen when patchwork is doing it)

There are quite a few threads that take longer than 1 second to load! but they are suffering from heavy duplications! just filtering that out speeds it up a lot, there are only a handful that have are more than 500 ms to load with duplicates removed. The number of duplicates is also quite surprising, some threads are loading over 1000 messages, even if there are actually only about 100 messages!

We can probably do some hack which at least prevents patchwork loading threads in an intolerable length of time to something tolerable, but I think if we can't really do this right we are failing at computers.

I think what would work much better, is if patchwork did a simpler query to get the messages in a thread (request only messages that link to the root, and then get backlinks and likes for each message)

**Comment by pfrazee** [comment]
Right, I agree about this. In ssbmail, I stopped using relatedMessages and filtered out the duplicates before transfer. The long threads load instantly.

I do think relatedMessages should be removed, because of the performance issue.

**Comment by dominictarr** [comment]
Great.

Part of the problem here is that there is a lot of coupling between patchwork-threads
and the ui. you can't just use a single method to load a thread, https://github.com/patchkit/patchkit-flat-msg-thread/blob/master/index.jsx#L103-L113 and then when preparing for the thread, you need to load the data for the messages too.

It would be better to load the base messages for the thread in one go, and then let the message renderer worry about likes and backlinks.

**Comment by dominictarr** [comment]
hmm, looking at this some more, edits are just about _messages_ right? that should also be a part of the message renderer not the thread too? @du5t

**Comment by du5t** [comment]
i was sort of intuitively thinking that way when i wrote [`reviseFlatThread`](https://github.com/ssbc/patchwork-threads/blob/master/index.js#L66): all it does is take each "post" in a thread and get the latest revision.

unfortunately, [`getLatestRevision`](https://github.com/ssbc/patchwork-threads/blob/master/index.js#L452) uses relatedMessages. this is because revisions are also a thread.

is this one of those situations where a linked list is a good primitive but a kv-store/other indexed thing on top is way better for the kind of use we're trying to put it to?

**Comment by dominictarr** [comment]
@du5t the trouble is that relatedMessages returns a tree, anyway it's not just a linked list, because we have the `root` message, so we can easily retrive everything in a thread. edits are a thread per message, though, correct?

**Comment by du5t** [comment]
that's right. and each edit has a [`revisionRoot`](https://github.com/ssbc/ssb-msg-schemas#ssb-message-schemas) according to the message schemas.

**Comment by pfrazee** [comment]
The reality is that any data structure that we treat as an recursive tree is going to have the exact same performance behaviors as `relatedMessages` does, given the indexes we currently create.

The problem is that you have to do a link-index query for each node in the tree. A rel-type filter improves the querytime but it doesn't change the scaling behavior; once you have enough posts, you'll have bad performance.

The only realistic solutions are 1) dont use datastructures that are loaded by recursion, or 2) precompute an index that lets you get a full tree structure in one query.

1 is a good solution for posts, it just means you have to have the `root` link set correctly on all replies, so that you get the replies in one go. You then only recurse one more step on each reply, to get things like likes (but not to get more posts).

**Comment by dominictarr** [comment]
@pfraze that's not quite right, because relatedMessages actually has a bug. It doesn't retrive a message for each node, it retrives a message for each _link_. in my measurement above, I show the number of messages retrived currently (column 3), and the number retrived if a check is added so that nothing is retrived twice (column 5), and as you see those numbers are often an order of magnitude different.

**Comment by pfrazee** [comment]
@dominictarr yeah that's what I was saying, it does a link-query for each node (message) in the tree, which means it's fetching one message for each link that relates to the tree.

This isn't quite the right place but it's related - I've been wondering about stripping the ssb api down to bare minimum, removing all the indexes, except maybe author. Then sbot wouldnt have a primary user (because decryption wouldnt be needed) and so all feed-publishing would be done by the app, and handed to sbot via `add()` instead of `publish()`. Just a thought.

**Comment by dominictarr** [comment]
the problem, though, is that patchwork threads currently _depends_ on that bug ;)

**Comment by pfrazee** [comment]
I've got code in ssbmail that could be a starting point for removing relatedMessages, but it'll take a little effort.

**Comment by keks** [comment]
Just to make sure I get this right, <300 subsequent leveldb requests take more than a second? I have trouble believing that it has to take that long.

**Comment by pfrazee** [comment]
Does seem to have weird results. Maybe it has to do with the size of the content. Look at these two entries:

```
#id loadtime count loadtime_dedup count_dedup
%Zundhf6gzpYAaePD+8DBeE7MDqull81LSCcTBfkGjPw=.sha256 1179 29 433 12
%7G0kC/rzBW0WXmC4SMlNNxTG9li0Iwucx2u91lBBMKg=.sha256 1351 839 301 77
```

**Comment by dominictarr** [comment]
you could get a relatively small amount of messages take a long time if the "tree" is more like a linked list, because it has to do many round trips. so if a thread mentions a thread which mentions a thread etc, (probably a message in that thread would be enough).

Also, my script just iterates over all the root messages in the db and tries to build all the threads, so they are all running at the same time and there will be statistical variation and if one heavy thread could slow down another request... so it wouldn't be a good idea to read to much into a single measurement.

**Comment by dominictarr** [comment]
I'd post that script... but it depends on a hack (that wouldn't actually be useful) in secure-scuttlebutt

**Comment by dominictarr** [comment]
@pfraze although I agree with https://github.com/ssbc/patchwork-threads/issues/11#issuecomment-218302198 sbot would still need a default user because it's gotta auth as someone during gossip.

**Comment by ralphtheninja** [comment]
Adding `%myUw6bjUEhkwp9FVmG5Ggae4UoyVma4jqrUthyxQI9Y=00=01sha256"` that causes OOM crash.

**Comment by ralphtheninja** [comment]
Also see https://github.com/ssbc/patchwork/issues/409

**Comment by du5t** [comment]
hahaha, [hello again](https://www.youtube.com/watch?v=HSmld6EE3ek).
