### ISSUE TITLE
threads are not ordered correctly.

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchwork-threads#2]
As evidenced in the recent post from MSDOS_Executive you cannot trust a timestamp.
Maybe we should have not have used timestamps.

Anyway, it has revealed two bugs: theads are not ordered correctly (should be ordered by branch links, then timestamps) and `getLastThreadPost` is also wrong (it chooses the latest by timestamp!)

Really, sometimes updates will be concurrent. in that case a branch should really be an array.

**Comment by pfrazee** [comment]
Ahem! https://github.com/ssbc/patchwork-threads/pull/1 (note item 2)

This is simply a bug with that algorithm, to do with the root message. 

`getLastThreadPost` does not choose by timestamp, it chooses by last in the flattened thread. Its bug is a reflection of the first bug

**Comment by pfrazee** [comment]
I've got some ideas for handling the bugs we have. We just have to be a bit judicious about our trust. TBH in I believe all we have available (with the global EC constraint) is
- Receive wall TS
- Asserted wall TS
- Happens-before content hashes

And I think that'll be enough, again just requires some... judiciousness, that's not yet encoded

**Comment by dominictarr** [comment]
If you put the hash of another message in your message that _proves_ it was before your message, otherwise you'd need to have a hash collision, though just because the hash was omitted doesn't mean it didn't happen before your message.

**Comment by pfrazee** [comment]
Yes that's what I was referring to with "Happens-before content hashes"

**Comment by dominictarr** [comment]
yes i just wanted the record to show that happens-before-proofs are a bit more reliable than the others.

One more idea: you can have global monotonic counter. it's like a sequence, but it increases +1 more than the latest number you have seen. if two peers get the same number that means that was a concurrent update. if we happen to see it in series then the number increments. hmm, although someone could still post a really really high number and the implications of that are a little bit hard to think about...

**Comment by pfrazee** [comment]
Yeah that's a lamport clock. I agree with that issue, I dont know if it gets us anything here
